idaholab/civet

ci/EventsStatus.py
ci/recipe/tests/test_RecipeRepoReader.py
ci/static/ci/css/base.css

Make continue lines a little better.

---

README.md

Putting a bit more info into the readme copied from the wiki so that people see what CIVET is when they land here.

Expanding Readme

---

ci/templates/ci/job.html
ci/tests/test_views.py
ci/views.py

Only show active clients on client page

---

ci/gitlab/views.py

GitLab sends an additional push event after a merge but it doesn't have any commits. Don't process this.

Be more selective in processing GitLab events.

---

ci/GitCommitData.py
ci/gitlab/tests/test_views.py
ci/gitlab/views.py
civet/settings.py

Fix GitLab issue with updates on merge requests

---

ci/client/tests/test_views.py
ci/client/views.py

Set PR status when auto cancelling

---

ci/templates/ci/recipe_events.html

Add links to bread crumb on recipe_events page

---

ci/client/UpdateRemoteStatus.py
ci/client/tests/test_views.py
ci/client/views.py
ci/models.py

Update Git status for jobs that won't run due to failed dependencies.

---

ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/models.py
ci/tests/test_models.py

Don't add the label if the event is a hard fail.

Only put a "Failed but Allowed" label if the event is FAILED_OK.

---

ci/PullRequestEvent.py
ci/bitbucket/api.py
ci/bitbucket/tests/test_api.py
ci/client/UpdateRemoteStatus.py
ci/client/tests/ClientTester.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/client/tests/test_views.py
ci/client/views.py
ci/git_api.py
ci/github/api.py
ci/gitlab/api.py
ci/gitlab/tests/test_api.py
ci/models.py
ci/tests/test_PullRequestEvent.py
ci/tests/test_models.py
civet/settings.py

Allow posting a PR comment with an event summary

---

ci/PushEvent.py
ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/client/views.py
ci/event.py
ci/tests/test_views.py
ci/views.py

Make sure Git server gets updated on job cancellation

---

ci/gitlab/api.py
ci/gitlab/tests/test_api.py

We were only checking projects/members and we
need to check groups/members as well.

Fix problem with getting project access level.

---

ci/Permissions.py
ci/ajax/tests/test_views.py
ci/ajax/views.py
ci/bitbucket/api.py
ci/bitbucket/tests/test_api.py
ci/git_api.py
ci/github/api.py
ci/github/tests/test_api.py
ci/gitlab/api.py
ci/gitlab/tests/test_api.py
ci/models.py
ci/oauth_api.py
ci/recipe/RecipeCreator.py
ci/recipe/RecipeReader.py
ci/recipe/RecipeWriter.py
ci/recipe/tests/recipe_private.cfg
ci/recipe/tests/test_RecipeCreator.py
ci/recipe/tests/test_RecipeReader.py
ci/tests/DBTester.py
ci/tests/test_Permissions.py
ci/tests/test_job_view_selenium.py
ci/tests/test_views.py
civet/settings.py

Add a team/group check to be able to see clients.
closes #273
closes #202

Add ability to specify teams that can view a job.

---

ci/Permissions.py
ci/client/ParseOutput.py

Update job status regex

---

client/JobRunner.py
client/tests/test_JobRunner.py

There were errors like:
Error:'ascii' codec can't decode byte 0xe2 in position 88467: ordinal not in range(128)

Fix output size check.

---

ci/bitbucket/api.py
ci/bitbucket/tests/test_api.py
ci/bitbucket/views.py
ci/management/commands/load_recipes.py
ci/templates/ci/base.html

Tested against a live installation and PRs, pushes, comments,
seemed to work.

Fix bitbucket support.

---

ci/static/ci/js/update.js
ci/tests/SeleniumTester.py

Fix PR sort

---

ci/bitbucket/views.py
ci/github/views.py
ci/gitlab/views.py
ci/models.py

Fix setting branch status.

---

ci/EventsStatus.py
ci/RepositoryStatus.py
ci/ajax/tests/test_views.py
ci/ajax/urls.py
ci/ajax/views.py
ci/templates/ci/base.html
ci/templates/ci/event.html
ci/templates/ci/job.html
ci/templates/ci/user.html
ci/tests/test_EventsStatus.py
ci/tests/test_RepositoryStatus.py
ci/tests/test_views.py
ci/urls.py
ci/views.py

Make a user specific page with open PRs

---

ci/PushEvent.py
ci/models.py
ci/recipe/RecipeCreator.py
ci/recipe/RecipeReader.py
ci/recipe/RecipeRepoReader.py
ci/recipe/tests/alt.cfg
ci/recipe/tests/recipe_extra.cfg
ci/recipe/tests/test_RecipeCreator.py
ci/recipe/tests/test_RecipeReader.py
ci/tests/DBTester.py
ci/tests/test_PushEvent.py
ci/tests/test_views.py

This was never being used and I don't think it even works.

Remove option to pattern match recipes on push

---

ci/bitbucket/api.py
ci/bitbucket/tests/test_api.py
ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/git_api.py
ci/github/api.py
ci/github/tests/test_api.py
ci/gitlab/api.py
ci/gitlab/tests/test_api.py
ci/models.py
ci/recipe/RecipeCreator.py
ci/recipe/RecipeReader.py
ci/recipe/tests/recipe_all.cfg
ci/recipe/tests/test_RecipeCreator.py

Allow creating/updating issues on job failure.

---

ci/github/api.py
ci/views.py

Immediately update Git status on job activation.

---

ci/tests/test_views.py
ci/views.py

When invalidating all jobs on an event, it didn't take
into account any job dependencies, it just started all the jobs.
Had the case where an event was invalidated and the "Precheck"
failed but all the other jobs were running. Updating the status
on GitHub got all weird because the checks we were doing said
that none of those jobs should be running.

Fix invalidate event.

---

ci/TimeUtils.py

This helps javascript sorting even when two events happen
in the same second.

Use microseconds in event sort string.

---

ci/ManualEvent.py
ci/models.py
ci/tests/test_views.py
ci/views.py

Allow scheduled events to not update branch status

---

ci/forms.py
ci/templates/ci/branch.html
ci/tests/test_views.py
ci/views.py

Allow selection of events to show on a branch.

---

Makefile

Add the htmlcov Makefile target

Improve dependencies in Makefile.

---

ci/EventsStatus.py
ci/client/views.py
ci/models.py
ci/tests/test_EventsStatus.py
ci/views.py

Add running step to job description

---

ci/bitbucket/api.py
ci/bitbucket/tests/test_api.py
ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/git_api.py
ci/github/api.py
ci/github/tests/test_api.py
ci/gitlab/api.py
ci/gitlab/tests/test_api.py
ci/models.py
civet/settings.py

This is based on attached labels on the PR.
closes #369

Enable an automerge for PRs on GitHub.

---

ci/templates/ci/pr.html
ci/views.py

On the PR page where you select optional recipes, it can be
useful to know which recipes run when a PR gets merged.

For optional recipes, show what branch they run on, if any

---

ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/models.py
ci/recipe/RecipeCreator.py
ci/recipe/RecipeReader.py
ci/recipe/tests/recipe_all.cfg

Add custom message on auto issue creation

---

Makefile
ci/client/views.py
ci/models.py
ci/recipe/RecipeCreator.py
ci/recipe/RecipeReader.py

for pull requests to be merged to when testing

add ability to manually specify an override base branch

---

ci/static/ci/css/base.css

This change allows applications to support prefer-color-scheme CSS switching.

Enable DarkMode media scheme

---

ci/static/ci/css/base.css

Fix a small radius glitch with tables

Adjust the colors a bit

---

ci/static/ci/css/base.css

Lots of boxes of different types means more tweaks to make it all
look right.

Fixes only found after applying to production server

---

ci/static/ci/css/base.css

Also, brighten up the canceled/nostatus statuses. They were a bit too dark when
using light mode.

Add missing canceled box status tag

---

ci/client/UpdateRemoteStatus.py
ci/client/tests/test_views.py
ci/client/views.py
ci/models.py
ci/static/ci/css/base.css
ci/templates/ci/base.html
ci/tests/test_models.py

This will allow a special return code (85) to trigger a new status
in Civet (Intermittent Failure).

Add Intermittent Failure feature

---

ci/static/ci/css/base.css

Increase the width of our Civet container page. Its... getting annoying.

Increase Container Width

---

client/Modules.py

Also, add checking for a system modulecmd.
(Fedora for example installs it in /usr/bin/modulecmd )

Adding list of modulecmds to try.

---

README.md
ci/views.py
client/Modules.py
client/tests/test_INLClient_live.py
client/tests/test_Modules.py

Sort client listing by active (seen in < 60 s) first

---

client/JobRunner.py

These changes were not needed.

Revert #519 and #518

---

client/inl_client.py
conda/build.sh

Adding SSL capabilities as a default to the conda package.

Have the server start with SSL upon activating

---

conda/build.sh

Limit nginx worker processors.
Create the SSL certificate as part of the activation process.

Limit nginx processes. Create SSL cert later

---

ci/oauth_api.py

@milljm this is needed for github.inl.gov auth

Add unique header to oauth api

---

Makefile
ci/client/ReadyJobs.py
ci/client/tests/test_get_cached_job.py
ci/client/tests/test_views.py
ci/client/urls.py
ci/client/views.py
ci/tests/test_PushEvent.py
civet/settings.py
client/BaseClient.py
client/INLClient.py
client/JobGetter.py
client/JobRunner.py
client/client.py
client/inl_client.py
client/settings.py
client/tests/claim_response.json
client/tests/test_BaseClient_live.py
client/tests/test_INLClient_live.py
client/tests/test_JobGetter.py
client/tests/test_JobGetter_live.py
client/tests/test_JobRunner.py
client/tests/test_client.py
client/tests/utils.py

Closes https://github.com/idaholab/civet/issues/570

Try to cache available jobs

---

ci/client/views.py
client/JobGetter.py

Fixes for #569

---

Makefile
ci/client/views.py
client/JobGetter.py

Fix lock context

---

client/client.py
client/tests/test_client.py

Store build key as an integer

---

ci/git_api.py

Catch invalid JSON

---

client/INLClient.py

refs https://github.com/idaholab/civet/issues/579

Also do a cleanup after the job is ran

---

client/INLClient.py

Update gitlab API for webhook pushes

---

ci/client/views.py

Use correct forwarded address

---

ci/client/tests/test_get_cached_job.py
ci/client/views.py

Closes #591
This enables us to set client build configs and let the ordering of those configs prioritize which jobs the client wants first. For example (which is what led to this), the GPU build boxes have a GPU config. However, when GPU configs aren't needed, it would be nice to let them run non-GPU configs. But, when GPU configs are in the queue, we want to prioritize running them over non-GPU configs.

Prioritize getting jobs by the build config ordering

---

ci/github/views.py

Ignore new github webhook actions

---

ci/github/views.py

Add converted_to_draft to skipped actions

---

ci/github/views.py

Add auto_merge_disabled to skipped actions

---

ci/github/views.py

Add locked to skipped actions

---

ci/client/ProcessCommands.py

Support multiple PR comments from a single job

---

ci/PullRequestEvent.py
ci/bitbucket/api.py
ci/bitbucket/tests/test_api.py
ci/client/UpdateRemoteStatus.py
ci/client/tests/test_views.py
ci/client/views.py
ci/event.py
ci/git_api.py
ci/github/api.py
ci/github/tests/test_api.py
ci/gitlab/api.py
ci/gitlab/tests/test_api.py
ci/models.py
civet/apps.py
conda/build.sh
conda/meta.yaml

For every 'thing' that Civet works on, update the statuses for said project/repo (not just PRs).

Update GitHub/GitLab with push statuses

---

ci/Permissions.py
ci/client/ReadyJobs.py
ci/client/tests/test_views.py
ci/client/views.py
ci/models.py
ci/templates/ci/event.html
ci/templates/ci/job.html
ci/tests/test_Permissions.py
ci/tests/test_event_view_selenium.py
ci/tests/test_job_view_selenium.py
ci/tests/test_views.py
ci/urls.py
ci/views.py

Add prioritize option to a job
