ci/PullRequestEvent.py
ci/client/UpdateRemoteStatus.py
ci/git_api.py
ci/github/api.py
ci/github/tests/test_api.py
ci/gitlab/api.py
ci/gitlab/tests/test_api.py

Allow the GitServer to determine if they need to post an PR update.
After the recent GitLab update it doesn't seem to like multiple updates on the same job so we need a way for only GitLab to tell if they need to post an update.

Add stages to the PR update API.

---

README.md
ci/tests/test_views.py
ci/urls.py
ci/views.py

Have endpoints for branch, repo, and branch status that use names rather than internal DB ids.
For example, for the branch status:
Instead of https://www.moosebuild.org/44/branch_status.svg
we can use https://www.moosebuild.org/idaholab/civet/devel/branch_status.svg
closes #204

Provide some user friendly endpoints

---

ci/client/tests/test_views.py
ci/client/urls.py
ci/client/views.py
ci/templates/ci/job_update.html

Just provide a simple form for updating the remote git status of a job.
This can be useful when the job status hasn't been set correctly due to git server timeouts, etc.

Provide endpoint for updating the remote job status

---

ci/PushEvent.py
ci/bitbucket/views.py
ci/github/views.py
ci/gitlab/views.py
ci/models.py
ci/recipe/RecipeCreator.py
ci/recipe/RecipeReader.py
ci/recipe/tests/recipe_all.cfg
ci/recipe/tests/test_RecipeCreator.py
ci/tests/test_PushEvent.py

This can be used to auto cancel certain jobs when, for example,
multiple merges to master happen in quick succession and we don't
want to run things like documentation, update submodules, etc.

Have ability to auto cancel jobs on previous push events.

---

client/client.py
client/inl_client.py
client/scripts/control.sh

For long running clients, when keeping it in /tmp, it can
be removed by the system cleanup of /tmp.

Change location of the client PID file from /tmp to $HOME.

---

ci/PullRequestEvent.py
ci/tests/test_PullRequestEvent.py

For MOOSE, we have the `DOCUMENTATION` label that matches documentation files.
Now that the docs are run on every PR, the match logic wasn't picking it up. So if
a PR only had documentation changes it would run everything.

Fix dynamic match for standard PR recipes.

---

ci/PullRequestEvent.py
ci/client/ProcessCommands.py
ci/client/UpdateRemoteStatus.py
ci/client/tests/test_ProcessCommands.py
ci/client/views.py
ci/views.py

Unless the name isn't unique (ie, we have "Test:linux-gnu" and "Test:mac-clang".
Also, add links to the job page when posting comments.

Don't include build config on PR status messages

---

ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py

Remove failed but allowed label when an event is complete and no tests

---

ci/bitbucket/api.py
ci/bitbucket/tests/test_api.py
ci/client/ProcessCommands.py
ci/client/tests/test_ProcessCommands.py
ci/github/api.py
ci/github/tests/test_api.py
ci/gitlab/api.py
ci/gitlab/tests/test_api.py
ci/tests/utils.py

This is intended for things like documentation where it don't necessarily want a new comment (and thus new email) every time the documentation tests complete.
Also for things like the clang format check where we really only need the latest warning but we do want to have the email sent.

Automated comments can replace or remove existing comments

---

ci/client/views.py
client/BaseClient.py
client/INLClient.py
client/JobRunner.py
client/tests/test_BaseClient_live.py
client/tests/test_INLClient_live.py
client/tests/test_JobRunner.py

This was primarily put in place to try to catch
the out of disk space error so that the client doesn't
keep trying new jobs and then failing immediately.

If the JobRunner has errors then exit the client.

---

ci/ManualEvent.py
ci/PullRequestEvent.py
ci/PushEvent.py
ci/client/UpdateRemoteStatus.py
ci/client/tests/test_ProcessCommands.py
ci/models.py
ci/tests/test_event.py

Fix call to process_commands that didn't pass in a URL.

Set job status to ACTIVATION_REQUIRED for non active jobs.

---

ci/bitbucket/api.py
ci/bitbucket/tests/test_api.py
ci/git_api.py
ci/github/api.py
ci/github/tests/test_api.py
ci/gitlab/api.py
ci/gitlab/tests/test_api.py
ci/management/commands/sync_open_prs.py
ci/models.py
ci/templates/ci/base.html
ci/tests/test_commands.py
ci/tests/test_views.py

Sometimes the PRs the git server and the PRs CIVET
thinks are open get out of sync due to failed events.
This automatically closes PRs that CIVET thinks
are open but have been closed on the Git server.
Also reports any open PRs on the Git server
that CIVET doesn't have open.
Added as a management command as this is mainly for admins.
For usage:
`./manage.py sync_open_prs --help`
Of interest is the `--dryrun` option that will just report what would have been done.
closes #331

Add a sync_open_prs management command.

---

ci/management/commands/load_recipes.py
ci/recipe/RecipeCreator.py
ci/recipe/tests/test_RecipeCreator.py

RecipeCreator.load_recipes() is an atomic operation so
we really shouldn't be doing network calls to git servers.

Separate out installing webhooks from recipe loading.

---

Makefile

Mainly so we don't introduce deprecated django calls/imports.

Make python warnings errors.

---

ci/EventsStatus.py
ci/tests/test_EventsStatus.py

problems with the event table.

Truncate long words in event description because it causes

---

ci/PushEvent.py
ci/client/tests/test_views.py
ci/client/urls.py
ci/client/views.py
ci/event.py
ci/models.py
ci/tests/test_PushEvent.py
ci/tests/utils.py

The idea is that once a push event starts running, it will run
to completion. When new events come in, events that are not
the "current" event will get cancelled. Also, the job
priorities behave differently on these events. Normal push
event jobs are sorted by priority and then by creation time.
On these special branches, event jobs are sorted by creation
time then priority. This causes all jobs on the "current" event
to run before jobs on newer events.
closes #389

On certain branches, handle push events using a "current" event.

---

ci/PullRequestEvent.py
ci/templates/ci/ajax_test.html

We want to create jobs as fast as possible so
that the clients can pick them up and for the
main page to be updated properly.
Right now we are doing an http request (post) to
update job status which can take a bit of time
and possibly timeout.

Move http requests after PR job creation.

---

ci/PullRequestEvent.py
ci/client/UpdateRemoteStatus.py
ci/event.py
ci/github/tests/test_views.py

On a PR, when a new event comes in, we would update
the PR status of the previously canceled jobs then
immediately set the PR status for the newly created
jobs. This takes a lot of time and can possibly trigger
GitHub rate limit abuse problems.

Reduce the number of git server update requests.

---

client/ServerUpdater.py
client/tests/test_ServerUpdater.py

Don't abort the civet client when the server has an internal server error

Better error handling in the client

---

ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/models.py
ci/tests/test_PushEvent.py
ci/tests/utils.py

If a previous event is cancelled but has an existing
failed job, there is no reason to uncancel it since
we know the event is going to fail. So go to the previous
event.

Improve event auto uncancel logic

---

ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/models.py

This doesn't seem to be needed since we will uncancel on
job failure. This causes problems since some jobs might
not uncancel (like timing). When they finish they might
uncancel an event that shouldn't be.

Remove the uncancelling on event completion.

---

ci/client/UpdateRemoteStatus.py
ci/client/tests/test_UpdateRemoteStatus.py
ci/management/commands/cancel_old_jobs.py
ci/models.py

If there is already a failed job on an event when a job fails
then we don't need to try to uncancel events since it should
have already been done.

Do a better job failed check when trying to uncancel an event

---

ci/bitbucket/tests/test_views.py
ci/bitbucket/views.py
ci/client/tests/test_views.py
ci/client/views.py
ci/github/tests/test_views.py
ci/github/views.py
ci/gitlab/tests/test_views.py
ci/gitlab/views.py
ci/models.py
ci/recipe/RecipeCreator.py
ci/recipe/RecipeReader.py
ci/recipe/tests/test_RecipeCreator.py
ci/tests/utils.py

This would allow setting an alternate user, other than the
build_user, that will run the civet client.

Allow a client_runner_user in the recipe

---

ci/RepositoryStatus.py
ci/client/UpdateRemoteStatus.py
ci/management/commands/sync_badges.py
ci/models.py
ci/static/ci/css/base.css
ci/static/ci/js/update.js
ci/templates/ci/repo_status.html
ci/tests/DBTester.py
ci/tests/test_RepositoryStatus.py
ci/tests/test_commands.py
ci/tests/test_models.py
ci/tests/utils.py
civet/settings.py

This associates a badge with a recipe, configurable in settings.py. When the latest job for that recipe completes it updates the badge status.
closes #423

Have repository badges based on job status

---

ci/templates/ci/events.html
ci/tests/test_views.py
ci/urls.py
ci/views.py

@aeslaughter 
This endpoint would be something like `civet.inl.gov/sha_events/idaholab/moose/12345`
Do you have the `idaholab/moose` part while building docs? I could leave that out and only use the SHA but there could be a (small) chance that it picks up other stuff.

Add endpoint to get events based on SHA

---

ci/static/ci/css/base.css

While being specified as 'unsupported' by the industry standard, as
well as Apple stating 'under development', we are going to enable
it because it is painful when it is not.

Enable touch based scrolling for job results

---

ci/static/ci/css/base.css

Failed_OK badge needs its own CSS for its increased size.

The badge "Failed_OK" is a bit larger

---

ci/static/ci/css/base.css
client/JobRunner.py

Intermittent Failure was causing recipes to halt, when they should
be treated as a success.
Add candy stripes to some statuses (cancel and intermittent failure)

Fix intermittent continuation

---

ci/models.py
ci/recipe/RecipeReader.py
ci/recipe/Recipe_Template.cfg

This PR prevents un-authorized users access to recipes which may not have automatic set.

Make authorized users the default 'automatic' setting

---

ci/static/ci/js/update.js

Only increase the event counter on table rows that are not continuation rows (which have an `_999` suffix in their element ID). 
Closes #462

Correctly count events in recent events table

---

ci/static/ci/js/update.js

#463 still counted too many rows. Instead of skipping rows with the `_999` suffix we now skip all rows that have a suffix (because it could be `_998`, `_997`, etc.).
Refs #462

Fix the recent event number fix

---

ci/views.py

Django has a utility for this:
https://github.com/django/django/blob/efc1c73bf511cbebf03fa5b13fa3a98718daf928/django/utils/text.py#L222
closes #471

Fix filenames in results tarballs

---

client/scripts/mingw64_runcmd.bat

This fixes a problem that RAVEN was having with running Civet in windows 10.

If bash is not found in WD, unset WD

---

requirements.txt

satisfy dependabot (Critical Vulnerability: Django)

Bump Django version

---

client/BaseClient.py
client/INLClient.py
client/JobRunner.py
client/inl_client.py
client/tests/test_BaseClient_live.py
client/tests/test_INLClient.py
client/tests/test_INLClient_live.py
client/tests/test_JobRunner.py

refs #579
Adds the `--[startup,exit,pre-job,post-job,pre-step,post-step]-command` arguments to the INL client so that we can run custom scripts at those entry points. This gives us a lot of flexibility for checking job state and cleaning things up, in particular for the HPC clients we're working on. The commands executed with `--[pre,post]-step-command` also get the main environment from the step (that is, from the recipe), so that we can also do conditional things based on variables that are set in the recipes.

Expand cleanup commands to stage commands

---

ci/static/ci/css/base.css

This adds the necessary class id to our badges that all the other class box statuses adheres to.
Also, make all the boxes the same size. We don't need failed but allowed to be "slightly larger".

Fix badges box sizes

---

client/JobRunner.py
client/tests/test_JobRunner.py

When something breaks usually we want to know "how was it set up" and "what broke", and we don't care so much about what happened in between. This should be much better for debugging than trimming the "what broke" part at the end of output.
I want to say this should be merged soon so we can dig into intermittent distcheck recipe issues like https://civet.inl.gov/job/2591793/ ... but really this should get some serious review and testing first, since I have neither a strong familiarity with python nor a local Civet setup to see what my infamiliarity broke.

Trim oversized output from the middle, not the end

---

ci/templates/ci/job.html

This has been bothering me for a while now. The spinner used on the job page is supposed to have a pulsed update rather than a smooth rotation.

Most important spinner update
